webtalk_init -webtalk_dir C:/Users/mehgul/LabVivado/Lab9_student/lab_9.sim/sim_1/behav/xsim/xsim.dir/MIPS_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed May 31 18:01:57 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212319763_174110940_0_529" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ed774d3e-759c-4a86-9e5a-31da7b9669af" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "7e17bd2c72234a3a8aac19d19ed497ee" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "43" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1160 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8900_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3450465415 -regid "212319763_174110940_0_529" -xml C:/Users/mehgul/LabVivado/Lab9_student/lab_9.sim/sim_1/behav/xsim/xsim.dir/MIPS_test_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/mehgul/LabVivado/Lab9_student/lab_9.sim/sim_1/behav/xsim/xsim.dir/MIPS_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/mehgul/LabVivado/Lab9_student/lab_9.sim/sim_1/behav/xsim/xsim.dir/MIPS_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
